[workspace]
exclude = [
  "autocorrect-tauri",
]
members = [
  "autocorrect",
  "autocorrect-wasm",
  "autocorrect-derive",
  "autocorrect-cli",
  "autocorrect-py",
  "autocorrect-node",
  "autocorrect-rb/ext/autocorrect",
]
