[package]
authors = ["Jason Lee <huacnlee@gmail.com>"]
description = "Automatically add whitespace between CJK (Chinese, Japanese, Korean) and half-width characters (alphabetical letters, numerical digits and symbols)."
edition = "2018"
homepage = "https://github.com/huacnlee/autocorrect"
keywords = ["auto-correct", "fmt", "format", "spacing"]
license = "MIT"
name = "autocorrect"
readme = "README.md"
repository = "https://github.com/huacnlee/autocorrect"
version = "1.0.0"

[lib]
name = "autocorrect"
path = "src/lib.rs"

[[bin]]
name = "autocorrect"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
assert-json-diff = "2.0.1"
clap = {version = "2.33.0", optional = true}
difference = "2.0"
glob = {version = "0.3", optional = true}
lazy_static = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.59"

[dev-dependencies]
pretty_assertions = "0.7.2"

[features]
bin = ["clap", "glob"]
