[package]
authors = ["Jason Lee <huacnlee@gmail.com>"]
description = "Automatically add whitespace between CJK (Chinese, Japanese, Korean) and half-width characters (alphabetical letters, numerical digits and symbols)."
edition = "2018"
homepage = "https://github.com/huacnlee/auto-correct.rs"
keywords = ["auto-correct", "fmt", "format", "spacing"]
license = "MIT"
name = "autocorrect"
readme = "README.md"
repository = "https://github.com/huacnlee/auto-correct.rs"
version = "0.4.2"

[lib]
name = "autocorrect"
path = "src/lib.rs"

[[bin]]
name = "autocorrect"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
clap = {version = "2.33", optional = true}
glob = {version = "0.3", optional = true}
html5ever = "0.25.1"
lazy_static = "1.4.0"
markup5ever = "0.10.0"
markup5ever_rcdom = "0.1.0"
regex = "1"

[features]
bin = ["clap", "glob"]
